### POST Request to create a patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name" : "John Doe with billing account",
  "email" : "test_01@example.com",
  "address": "123 main street",
  "dateOfBirth": "1990-12-31",
  "registeredDate": "2025-11-09"
}

###